childPipelines:
  scmUrls:
    - git@github.com:jithine/external-config-child1.git
jobs:
  main:
    image: node:12
    steps:
        - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET
